### PR TITLE
Fix links and refs in documentation

### LINKED ISSUE #1345: Fix links in docs
## Describe the bug
Many (all?) of the links in the docs which link from one tutorial to another do not work. some dont show up as links, some do but the links have the wrong path.

### PR DESCRIPTION
**Pull request by AlexisRenchon**
This PR fix broken links in documentation tutorials, and properly references the literature. 
It makes use of Documenter.jl `@ref`, DocumenterInterLinks `@extref`, and DocumenterCitations `@citet` instead of hardcoding. 

closes #1345 
closes #256 

https://clima.github.io/ClimaLand.jl/previews/PR1413/

### CODE REVIEW

File: docs/src/tutorials/standalone/Usage/domain_tutorial.jl [hunk 1]
```diff
@@ -54,13 +54,13 @@ underlying infrastructure in both cases.
...
 A variety of concrete domain types are supported:
 
-- 0D: [`Domains.Point`](https://clima.github.io/ClimaLand.jl/stable/APIs/shared_utilities/#ClimaLand.Domains.Point)
-- 1D: [`Domains.Column`](https://clima.github.io/ClimaLand.jl/stable/APIs/shared_utilities/#ClimaLand.Domains.Column)
-- 2D: [`Domains.Plane`](https://clima.github.io/ClimaLand.jl/stable/APIs/shared_utilities/#ClimaLand.Domains.Plane), [`Domains.SphericalSurface`](https://clima.github.io/ClimaLand.jl/stable/APIs/shared_utilities/#ClimaLand.Domains.SphericalSurface)
-- 3D: [`Domains.HybridBox`](https://clima.github.io/ClimaLand.jl/stable/APIs/shared_utilities/#ClimaLand.Domains.HybridBox), [`Domains.SphericalShell`](https://clima.github.io/ClimaLand.jl/stable/APIs/shared_utilities/#ClimaLand.Domains.SphericalShell).
+- 0D: [`Domains.Point`](@ref ClimaLand.Domains.Point)
+- 1D: [`Domains.Column`](@ref ClimaLand.Domains.Column)
+- 2D: [`Domains.Plane`](@ref ClimaLand.Domains.Plane), [`Domains.SphericalSurface`](@ref ClimaLand.Domains.SphericalSurface)
+- 3D: [`Domains.HybridBox`](@ref ClimaLand.Domains.HybridBox), [`Domains.SphericalShell`](@ref ClimaLand.Domains.SphericalShell).
```
Comment (ph-kev) [inline docs/src/tutorials/standalone/Usage/domain_tutorial.jl:63]: All of the `@ref` in this file doesn't work.

**Review by ph-kev — CHANGES_REQUESTED** [review]

**Comment by ph-kev** [comment]
I was taking a look at https://fredrikekre.github.io/Literate.jl/v2/generated/example/ and it should be possible to include `@ref`, but I am not sure how.

**Comment by ph-kev** [comment]
> I was taking a look at https://fredrikekre.github.io/Literate.jl/v2/generated/example/ and it should be possible to include `@ref`, but I am not sure how.

This is happening because `documenter = false`.

https://github.com/CliMA/ClimaLand.jl/blob/fa3ee9d57b7c35d26fc12e3ea096922f575693a7/docs/make.jl#L32-L36

File: docs/make.jl [hunk 2]
```diff
@@ -5,9 +5,24 @@ using Distributed
...
+    "ClimaCore" => "https://clima.github.io/ClimaCore.jl/dev/objects.inv",
+    "Documenter" => "https://documenter.juliadocs.org/stable/objects.inv",
+    # ClimaCoupler does not generate objects.inv for some reason
+    #                   "ClimaCoupler" => "https://clima.github.io/ClimaCoupler.jl/dev/objects.inv",
+);
+
+@everywhere bib = CitationBibliography(
+    joinpath(@__DIR__, "src", "refs.bib");
+    style = :numeric,
+)
```
[the remark this answers is not in the document]
Comment (AlexisRenchon) [reply docs/make.jl:24]: I agree. Having a look

File: docs/src/tutorials/standalone/Usage/domain_tutorial.jl [hunk 3]
```diff
@@ -74,7 +74,7 @@ As discussed above, our modeling requires that variables of a model can be defin
 
 There is a single key method which take a ClimaLand domain as an argument.
 
-- [` coordinates(domain)`](https://clima.github.io/ClimaLand.jl/stable/APIs/shared_utilities/#ClimaLand.Domains.coordinates): under the hood, this function  uses
+- [` coordinates(domain)`](@ref ClimaLand.Domains.coordinates): under the hood, this function  uses
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Usage/domain_tutorial.jl:77]: Later in this file, could we change this line?
"a Point domain only has a coordinate z_sfc (surface only). Column domains have a surface coordinate of z_sfc" -> "a Point domain only has a coordinate z\_sfc (surface only). Column domains have a surface coordinate of z\_sfc"?

I noticed that in the rendered page, it is interpreting the underscores as indicating italics

Comment (kmdeck) [reply docs/src/tutorials/standalone/Usage/domain_tutorial.jl:77]: Likewise for "The user still must define the prognostic\_domain\_names method"

File: docs/src/tutorials/standalone/Usage/LSM_single_column_tutorial.jl [hunk 4]
```diff
@@ -1,5 +1,5 @@
 # The `AbstractModel`
-# [tutorial](https://clima.github.io/ClimaLand.jl/stable/generated/model_tutorial)
+# [tutorial](@ref "General setup")
 # describes how a user can run
 # simulations of a physical system governed by differential equations.
 # In this framework, the user must define a model type for their problem,
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Usage/LSM_single_column_tutorial.jl:5]: Minor, but for the soil model code link, could we link to the richards equation file instead?
rre.jl

Comment (AlexisRenchon) [reply docs/src/tutorials/standalone/Usage/LSM_single_column_tutorial.jl:5]: Will do!

File: docs/src/tutorials/standalone/Soil/soil_energy_hydrology.jl [hunk 5]
```diff
@@ -111,7 +111,7 @@ earth_param_set = LP.LandParameters(FT);
 ν_ss_gravel = FT(0.0);
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Soil/soil_energy_hydrology.jl:111]: I noticed that the richards equation tutorial does not link correctly (at the very beginning of the file)

File: docs/src/tutorials/standalone/Soil/phase_change_analytic.jl [hunk 6]
```diff
@@ -211,7 +211,7 @@ z = parent(soil.domain.fields.z)[:];
 lines!(ax1, sol_T, z, label = "Model", color = :blue, linewidth = 3)
 
 # # Analytic Solution of Neumann
-# All details here are taken from [DallAmico2011](@cite) (see also [CarslawJaeger](@cite)), and the reader is referred to that
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Soil/phase_change_analytic.jl:214]: Link to https://clima.github.io/ClimaLand.jl/previews/PR1413/generated/standalone/Soil/phase_change_analytic/@ref%20Soil/soil_energy_hydrology.md does not work

File: docs/src/tutorials/standalone/Soil/freezing_front.jl [hunk 7]
```diff
@@ -69,7 +69,7 @@
 
 # `` ϑ_l(t = 0, z) = 0.33 ``.
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Soil/freezing_front.jl:71]: First link in the file (to the other tutorial) does not work https://clima.github.io/ClimaLand.jl/previews/PR1413/generated/standalone/Soil/freezing_front/@ref%20Soil/soil_energy_hydrology.md

File: docs/src/tutorials/standalone/Soil/evaporation.jl [hunk 8]
```diff
@@ -1,7 +1,7 @@
 # This sets up the simulation that mimicks the coarse sand
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Soil/evaporation.jl:1]: We can add a title

File: docs/src/tutorials/standalone/Soil/changing_soil_parameterizations.jl [hunk 9]
```diff
@@ -14,8 +14,7 @@
 # The `ConstantTwoBandSoilAlbedo` parameterization is useful for cases where the soil albedo is
 # known to be constant over time, such as in some idealized simulations or when using a fixed albedo value.
 
-# CLM reference: Lawrence, P.J., and Chase, T.N. 2007. Representing a MODIS consistent land surface in the Community Land Model
-# (CLM 3.0). J. Geophys. Res. 112:G01023. DOI:10.1029/2006JG000168.
+# CLM reference: [LawrenceChase2007](@citet)
 
 # First we import the necessary Julia packages:
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Soil/changing_soil_parameterizations.jl:19]: Link to "getting started" tutorial does not work

File: docs/src/tutorials/standalone/Canopy/default_canopy.jl [hunk 10]
```diff
@@ -9,7 +9,7 @@
 # and we'll highlight the changes between them.
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Canopy/default_canopy.jl:9]: "getting started" link does not work

File: docs/src/tutorials/standalone/Canopy/changing_canopy_parameterizations.jl [hunk 11]
```diff
@@ -1,5 +1,5 @@
 # # Changing Canopy Parameterizations
-# In [Default Canopy](docs/src/tutorials/standalone/Canopy/default_canopy.jl), we ran a simple canopy model simulation
+# In [Default Canopy](@ref "Canopy Model and Parameters"), we ran a simple canopy model simulation
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Canopy/changing_canopy_parameterizations.jl:2]: Im not sure if this is the correct link - I think we want to link to the other tutorial

**Review by kmdeck — APPROVED** [review]
this looks great! The references are really nice. thank you!

I just noticed a couple of the links between tutorials did not work and noted them in the review

File: docs/src/tutorials/standalone/Soil/layered_soil.jl [hunk 12]
```diff
@@ -1,7 +1,6 @@
 # This shows how to run single column soil model, in standalone mode
```
[the remark this answers is not in the document]
Comment (kmdeck) [reply docs/src/tutorials/standalone/Soil/layered_soil.jl:3]: "Soil with vertically changing properties" ?

File: docs/src/tutorials/standalone/Usage/LSM_single_column_tutorial.jl [hunk 13]
```diff
@@ -1,5 +1,5 @@
 # The `AbstractModel`
-# [tutorial](@ref "General setup")
+# [tutorial](@ref "Hydrostatic Equilibrium test for Richards Equation")
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Usage/LSM_single_column_tutorial.jl:2]: I think we want to refer to this one (which also needs a title?) https://clima.github.io/ClimaLand.jl/stable/generated/standalone/Usage/model_tutorial/

Comment (kmdeck) [reply docs/src/tutorials/standalone/Usage/LSM_single_column_tutorial.jl:2]: the title could be "Creating a Model"?

File: docs/src/tutorials/standalone/Canopy/default_canopy.jl [hunk 14]
```diff
@@ -1,5 +1,5 @@
 # # Default Canopy Model Tutorial
-# Now that we've run a simple default soil model simulation in [Getting Started](@ref getting_started.md),
+# Now that we've run a simple default soil model simulation in [Getting Started](@ref "Hydrostatic Equilibrium test for Richards Equation"),
```
Comment (kmdeck) [inline docs/src/tutorials/standalone/Canopy/default_canopy.jl:2]: This page: https://clima.github.io/ClimaLand.jl/stable/getting_started/

**Review by ph-kev — APPROVED** [review]
I think there is only one more warning related to the references that should be fixed.

```julia
 ┌ Warning: Cannot resolve @ref for md"[BucketModel](@ref ClimaLand.BucketModel)" in docs/src/generated/standalone/Bucket/coupled_bucket.md.
│ - No docstring found in doc for binding `ClimaLand.BucketModel`.
```
