### PR TITLE
store bareground albedo

### LINKED ISSUE #472: next_albedo bug with snow
## Describe the bug
In the function and static map albedo cases, we initialize `p.bucket.alpha_sfc` as the fixed ground albedo, then update it with the [next_albedo](https://github.com/CliMA/ClimaLSM.jl/blob/ab2ee9b20879694ea9c6310a43edfbbe57739179/src/standalone/Bucket/Bucket.jl#L592) function. However, in `next_albedo`, `alpha_sfc` is calculated as a function of `alpha_sfc` and `alpha_snow` when it should be a function of `alpha_ground` and `alpha_snow`.

This would cause a problem, e.g. if it were to snow for a while, where `alpha_sfc` would always increase towards `alpha_snow` and never decrease below its current value. Even if the snow melted entirely, the albedo wouldn't decrease below `alpha_sfc`, though we would want it to decrease to `alpha_ground`

### PR DESCRIPTION
**Pull request by juliasloan25**
## Purpose 
Store bareground albedo for albedo types that require bareground and snow albedo (`BulkAlbedoFunction` and `BulkAlbedoStatic`, but not `BulkAlbedoTemporal`). This allows us to remove the surface albedo that was previously stored in these two objects.

closes #472

## Content
- [x] add `\alpha_bareground` to `BulkAlbedoFunction/Static`
- [x] remove `\alpha_sfc` from `BulkAlbedoFunction/Static`
- [x] set `\alpha_bareground` (a Field) in albedo object constructor, using either function or input file
- [x] use `\alpha_bareground` to set `p.bucket.\alpha_sfc` in set_initial_parameter_field
- [x] use `\alpha_bareground` instead of `\alpha_sfc` in `next_albedo`
- [x] update for `BulkAlbedoFunction` constructor interface change (needs space now)
- [x] remove `set_initial_parameter_field` - calculations handled in `next_albedo`
- [x] update tests to check correct snow fraction update

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

File: src/standalone/Bucket/Bucket.jl [hunk 1]
```diff
@@ -65,51 +65,60 @@ abstract type AbstractBucketModel{FT} <: AbstractExpModel{FT} end
...
+function BulkAlbedoFunction{FT}(
+    α_snow::FT,
+    α_bareground::F,
+) where {FT <: AbstractFloat, F}
+    BulkAlbedoFunction(α_snow, α_bareground)
 end
 
 function BulkAlbedoFunction{FT}(
     α_snow::FT,
     α_sfc::Function,
```
Comment (kmdeck) [inline src/standalone/Bucket/Bucket.jl:92]: maybe we should also call this alpha_bareground for clarity?

Comment (kmdeck) [reply src/standalone/Bucket/Bucket.jl:92]: i guess we cant quite call it that, but maybe something similar instead of `sfc`

File: src/standalone/Bucket/Bucket.jl [hunk 2]
```diff
@@ -389,8 +402,8 @@ function set_initial_parameter_field!(
     p,
     surface_coords,
 ) where {FT}
-    (; α_sfc) = albedo
-    @. p.bucket.α_sfc = α_sfc(surface_coords)
+    # TODO should we include snow here?
```
Comment (kmdeck) [inline src/standalone/Bucket/Bucket.jl:405]: I think yes, for the Function and the Static cases. the surface albedo in those cases is the linear combination of bareground & snow albedo

Comment (kmdeck) [reply src/standalone/Bucket/Bucket.jl:405]: wait - can we get rid of the `set_initial_parameter_field` altogether? In update aux we will compute the linear combination and update p.bucket.alpha_surface for all models.

Comment (kmdeck) [reply src/standalone/Bucket/Bucket.jl:405]: I think we can for the Static and Function cases, because we have already set the bareground parameter field in the constructor. but we have to see if `next_albedo` does the right thing in this case: https://github.com/CliMA/ClimaLand.jl/blob/f05f861a8eed75d45cc0686333333b912137260b/src/standalone/Bucket/Bucket.jl#L452

File: src/standalone/Bucket/Bucket.jl (hunk 1 above)
Comment (juliasloan25) [reply src/standalone/Bucket/Bucket.jl:92]: good point! what about `alpha_bareground_func`?

File: src/standalone/Bucket/Bucket.jl (hunk 2 above)
Comment (juliasloan25) [reply src/standalone/Bucket/Bucket.jl:405]: I think we can! I changed the logic for next_albedo to handle the initialization case and verified locally that it produces the same field as the current `set_initial_parameter_field!`

File: docs/tutorials/standalone/Bucket/bucket_tutorial.jl [hunk 3]
```diff
@@ -168,6 +168,17 @@ import ClimaLand
...
+# resolution as the atmosphere, the bucket horizontal resolution would match the
+# horizontal resolution at the lowest level of the atmosphere model. In general, however, the two
+# resolutions do not need to match. Here we just set up something
+# simple - a Column.
+soil_depth = FT(3.5);
+bucket_domain = Column(; zlim = (-soil_depth, FT(0.0)), nelements = 10);
+surface_space = bucket_domain.space.surface
+
 # Define our `BulkAlbedoFunction` model using a constant surface and snow albedo:
 # The surface albedo is a function of coordinates, which would be
```
Comment (kmdeck) [inline docs/tutorials/standalone/Bucket/bucket_tutorial.jl:183]: small change - should these `surface` references be `bareground` now?

File: experiments/standalone/Bucket/global_bucket.jl [hunk 4]
```diff
@@ -41,9 +41,22 @@ context = ClimaComms.context()
...
+    radius = FT(6.3781e6),
+    depth = soil_depth,
+    nelements = (10, 10),
+    npolynomial = 1,
+    dz_tuple = FT.((1.0, 0.05)),
+);
+surface_space = bucket_domain.space.surface
+
+# Set up parameters
 α_sfc = (coordinate_point) -> 0.2;
```
Comment (kmdeck) [inline experiments/standalone/Bucket/global_bucket.jl:57]: likewise here

File: src/standalone/Bucket/Bucket.jl [hunk 5]
```diff
@@ -601,11 +524,12 @@ function next_albedo(
...
     t,
 ) where {FT}
-    (; α_snow) = model_albedo
+    (; α_snow, α_bareground) = model_albedo
     (; σS_c) = parameters
-    α_sfc = p.bucket.α_sfc
     σS = Y.bucket.σS
-    return @. ((1 - σS / (σS + σS_c)) * α_sfc + σS / (σS + σS_c) * α_snow)
+    return @. (
+        (1 - σS / (σS + σS_c)) * α_bareground + σS / (σS + σS_c) * α_snow
```
Comment (kmdeck) [inline src/standalone/Bucket/Bucket.jl:531]: yay! this is much clearer than how we had it before :)

File: test/standalone/Bucket/snow_bucket_tests.jl [hunk 6]
```diff
@@ -28,7 +28,6 @@ for FT in (Float32, Float64)
     earth_param_set = create_lsm_parameters(FT)
     α_sfc = (coordinate_point) -> 0.2 # surface albedo, spatially constant
```
Comment (kmdeck) [inline test/standalone/Bucket/snow_bucket_tests.jl:29]: could be alpha_bareground_func now

File: docs/src/APIs/Bucket.md [hunk 7]
```diff
@@ -23,7 +23,6 @@ ClimaLand.Bucket.beta_factor
 ## Methods for handling parameters read in from NetCDF files
 
 ```@docs
-ClimaLand.Bucket.set_initial_parameter_field!
 ClimaLand.Bucket.update_soil_albedo
```
Comment (kmdeck) [inline docs/src/APIs/Bucket.md:26]: is this defined?

**Review by kmdeck — APPROVED** [review]
looks good, Julia! thank you.

File: docs/tutorials/standalone/Bucket/bucket_tutorial.jl (hunk 3 above)
Comment (juliasloan25) [reply docs/tutorials/standalone/Bucket/bucket_tutorial.jl:183]: good point! I'll change it in all the drivers + tests
